import 'package:fatha/LangVar.dart';
import 'package:shared_preferences/shared_preferences.dart';
String langVar;
String smallLearn;
String largeLearn;
String newLearn;
String readNow;
String setting;
String submit;
String about;
String home;
String backHome;
String finish;
String reReading;
String wrong;
String recording;
String processing;
String rightReading;
String good;
String chooseLang;
String contact;
String invite;
String rate;
String name;
String phone;
String msg;
String send;
String problem;
String sendContac;
String settings;
String arabic;
String lang;
String selectLang;
String wrongWord;
String nextVerse;
String nextWord;
String enterName;
String enterPhone;
String enterMsg;
String sendContact;
Future<void> getCurrentLang(setState)async{
  SharedPreferences preferences= await SharedPreferences.getInstance();
  setState((){
    langVar = preferences.get("lang");
  submit= langVar=='en'?"Submit":"تأكيد";
   smallLearn= langVar=='en'?"Learn Fatiha for the little one":"تعلم الفاتحة للصغير";
   largeLearn= langVar=='en'?"Mastering the Fatihah for the Great":"تعلم الفاتحة للكبير";
   newLearn=langVar=='en'?"Teaching Al-Fatiha for a new Muslim":"تعلم الفاتحة للمسلم الجديد";
   readNow=langVar=='en'?"Read Now":"اقرأ الان";
   setting=langVar=='en'?"Setting":"الإعدادات";
   about=langVar=='en'?"About App":"عن التطبيق";
   home=langVar=='en'?"Home":"الرئيسية";
   backHome= langVar=='en'?"Back To Home":"الرجوع للرئيسية";
   finish= langVar=='en'?"Finished":"تم الإنتهاء";
   reReading=langVar=='en'?"Re Reading":"أعد القراءة";
   wrong= langVar=='en'?"Wrong Reading":"قراءة خاطئة";
  recording= langVar=='en'?"Recording ...":"... جاري التسجيل";
   processing=langVar=='en'? "processing ...":"... جاري المعالجة";
  rightReading=langVar=='en'? "Right Reading":"قراءة صحيحة";
  good= langVar=='en'?"Good !":"أحسنت !";
  chooseLang=langVar=='en'? "Choose A Language":"اختر اللغة";
   contact= langVar=='en'?"Contact Us":"اتصل بنا";
  invite= langVar=='en'?"Invite Your Friends":"اخبر أصدقائك";
  rate= langVar=='en'?"Rate This App":"قيم هذا التطبيق";
  name= langVar=='en'?"Name":"الاسم";
  phone= langVar=='en'?"Phone Number":"رقم الهاتف";
  msg=langVar=='en'? "Message":"الرسالة";
  send=langVar=='en'? "Send":"ارسال";
  problem= langVar=='en'?"No voice recognized..Reread":"لم يتم التعرف علي الصوت..أعد القراءة";
  sendContac= langVar=='en'?"contact Added Successfully":"السياسات و الشروط";
  settings=langVar=='en'?"Settings":"الإعدادات";
  arabic= langVar=='en'?"Arabic":"عربي";
  lang= langVar=='en'?"Language":"اللغة";
  selectLang=langVar=='en'? "Select App Language":"اختر اللغة";
  wrongWord= langVar=='en'?"Wrong Word":"كلمة خاطئة";
  nextVerse= langVar=='en'?"Next Verse":"الاية التالية";
  nextWord=langVar=='en'? "Next Word":"الكلمة التالية";
  enterName= langVar=='en'?"please Enter Your Name":"من فضلك أدخل الاسم";
  enterPhone= langVar=='en'?"please Enter Your Phone Number":"من فضلك أدخل رقم هاتفك";
  enterMsg= langVar=='en'?"please Enter Your Message":"من فضلك أدخل رسالتك";
  sendContact= langVar=='en'?"sent successfully":"تم الإرسال بنجاح";
  });
}
